name: Playwright tests
on:
  push:
    branches: ['main']

jobs:
  playwright-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Run GAD in Docker Image
        run: docker run -p 3000:3000 -d jaktestowac/gad

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Chromium Browser
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test

      - name: Archive tests results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            ./playwright-report/**/*.*
            ./test-results/**/*.*
